import type { Appointment, Barber, DayItem } from "./calendar-types";

export const MOCK_BARBERS: Barber[] = [
  {
    id: "barber-1",
    name: "Mike Johnson",
    workingHours: "09:00–10:40",
    avatar:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "barber-2",
    name: "Mike Johnson",
    workingHours: "09:00–10:40",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  },
];

export const MOCK_DAYS: DayItem[] = [
  {
    dayName: "Mon",
    dateNumber: 14,
    fullDateStr: "2026-07-14",
    date: new Date("2026-07-14"),
  },
  {
    dayName: "Tue",
    dateNumber: 15,
    fullDateStr: "2026-07-15",
    date: new Date("2026-07-15"),
  },
  {
    dayName: "Wed",
    dateNumber: 16,
    fullDateStr: "2026-07-16",
    date: new Date("2026-07-16"),
  },
  {
    dayName: "Thu",
    dateNumber: 17,
    fullDateStr: "2026-07-17",
    date: new Date("2026-07-17"),
  },
  {
    dayName: "Fri",
    dateNumber: 18,
    fullDateStr: "2026-07-18",
    date: new Date("2026-07-18"),
  },
  {
    dayName: "Sun",
    dateNumber: 19,
    fullDateStr: "2026-07-19",
    date: new Date("2026-07-19"),
  },
  {
    dayName: "Sat",
    dateNumber: 20,
    fullDateStr: "2026-07-20",
    date: new Date("2026-07-20"),
  },
];

const generateDayAppointments = (dateStr: string): Appointment[] => [
  {
    id: `appt-${dateStr}-1`,
    barberId: "barber-1",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T07:30:00`,
    endTime: `${dateStr}T08:30:00`,
    timeDisplay: "07:30 – 08:30",
    userName: "Alex Rivera",
    serviceName: "Beard trim & lineup",
    cardType: "appointment",
    bgColor: "#EBF5FF",
    durationMinutes: 60,
  },
  {
    id: `appt-${dateStr}-2`,
    barberId: "barber-1",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T09:00:00`,
    endTime: `${dateStr}T10:40:00`,
    timeDisplay: "09:00 – 10:40",
    userName: "Mike Johnson",
    serviceName: "• Classic men's haircut",
    cardType: "appointment",
    status: "completed",
    bgColor: "#FFFDE7",
    durationMinutes: 100,
  },
  {
    id: `appt-${dateStr}-3`,
    barberId: "barber-2",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T09:00:00`,
    endTime: `${dateStr}T10:40:00`,
    timeDisplay: "09:00 – 10:40",
    userName: "Mike Johnson",
    serviceName: "• Classic men's haircut",
    cardType: "appointment",
    bgColor: "#EBF5FF",
    durationMinutes: 100,
  },
  {
    id: `appt-${dateStr}-4`,
    barberId: "barber-1",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T09:00:00`,
    endTime: `${dateStr}T09:45:00`,
    timeDisplay: "09:00 – 09:45",
    serviceName: "Time reservation",
    cardType: "reservation",
    bgColor: "#F3F4F6",
    durationMinutes: 45,
  },
  {
    id: `appt-${dateStr}-5`,
    barberId: "barber-1",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T11:00:00`,
    endTime: `${dateStr}T12:00:00`,
    timeDisplay: "11:00 – 12:00",
    serviceName: "Revitalizing facial treatment",
    subTitle: "Classic men's haircut • 60 min",
    cardType: "appointment",
    bgColor: "#EBF5FF",
    durationMinutes: 60,
  },
  {
    id: `appt-${dateStr}-6`,
    barberId: "barber-2",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T11:30:00`,
    endTime: `${dateStr}T12:30:00`,
    timeDisplay: "11:30 – 12:30",
    userName: "David Miller",
    serviceName: "Haircut & Hot Towel Shave",
    cardType: "appointment",
    bgColor: "#FFFDE7",
    durationMinutes: 60,
  },
  {
    id: `appt-${dateStr}-7`,
    barberId: "barber-1",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T13:00:00`,
    endTime: `${dateStr}T14:00:00`,
    timeDisplay: "13:00 – 14:00",
    serviceName: "Staff Break / Lunch",
    cardType: "reservation",
    bgColor: "#F3F4F6",
    durationMinutes: 60,
  },
  {
    id: `appt-${dateStr}-8`,
    barberId: "barber-1",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T14:30:00`,
    endTime: `${dateStr}T15:30:00`,
    timeDisplay: "14:30 – 15:30",
    userName: "Ethan Hunt",
    serviceName: "Executive Grooming Package",
    subTitle: "Haircut + Beard + Scalp Massage",
    cardType: "appointment",
    bgColor: "#EBF5FF",
    durationMinutes: 60,
  },
  {
    id: `appt-${dateStr}-9`,
    barberId: "barber-2",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T15:00:00`,
    endTime: `${dateStr}T16:00:00`,
    timeDisplay: "15:00 – 16:00",
    userName: "Carlos Santana",
    serviceName: "Skin Fade & Hair Styling",
    cardType: "appointment",
    status: "completed",
    bgColor: "#FFFDE7",
    durationMinutes: 60,
  },
  {
    id: `appt-${dateStr}-10`,
    barberId: "barber-1",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T16:30:00`,
    endTime: `${dateStr}T17:30:00`,
    timeDisplay: "16:30 – 17:30",
    userName: "James Wilson",
    serviceName: "Buzz Cut & Shape-Up",
    cardType: "appointment",
    bgColor: "#EBF5FF",
    durationMinutes: 60,
  },
  {
    id: `appt-${dateStr}-11`,
    barberId: "barber-2",
    barberName: "Mike Johnson",
    startTime: `${dateStr}T17:00:00`,
    endTime: `${dateStr}T18:00:00`,
    timeDisplay: "17:00 – 18:00",
    userName: "Robert Chen",
    serviceName: "Beard Sculpting & Oil Therapy",
    cardType: "appointment",
    bgColor: "#FFFDE7",
    durationMinutes: 60,
  },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  ...generateDayAppointments("2026-07-14"),
  ...generateDayAppointments("2026-07-15"),
  ...generateDayAppointments("2026-07-16"),
  ...generateDayAppointments("2026-07-17"),
  ...generateDayAppointments("2026-07-18"),
  ...generateDayAppointments("2026-07-19"),
  ...generateDayAppointments("2026-07-20"),
  ...generateDayAppointments("2026-07-26"),
];
